### ISSUE TITLE
APACTestDrive/CloudNative_Mobile is ready for test

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#11]
APACTestDrive/CloudNative_Mobile is ready for test. 

@choichi let me know when you want to start the test. I'll clean up the environment for you.

**Comment by choichi** [comment]
Thank you Heung Sir
Let me finish the ICS lab together by latest tonight or Tmp morning then we can start testing  :)

**Comment by heungheung** [comment]
Do you want me to do some simple stuff in the JCS code?

**Comment by choichi** [comment]
You mean code to call MCS notification Restful? 
I temporarily put some simple html title code change in the lab, to be updated later
Well I haven't push Kwan's loyaltyMgmt code to github here yet...

**Comment by heungheung** [comment]
1. Preserve post data from search # of customer with X points of more -> to -> create offer
2. Jquery day selection
3. Post create offer insert SQL
4 addition touch up.... may be additional pages

**Comment by choichi** [comment]
Sure yes and thanks. 
We can split and leave some code enhancement to me, pick any and let me know to follow up.

**Comment by heungheung** [comment]
Commit and push what you have to **DevCS**.

Start create **branch** if you need to add/modify something. 

Let's start real use of DevCS / agile ::smile::

**Comment by heungheung** [comment]
@choichi Please use **10916** to test. Access until **July 14**. Environment is **CLEAN**. 
- DevCS contains one **EMPTY** project `APAC Cloud Test Drive - Dry Run`, no repo, no build, no deploy
- ACCS is clean, no instance
- JCS is clean, no instance
- DBCS contains the seed DB with data.

by the way, I'm using cloud.admin (with my icon).... you can pick any user.... the project is created by john.dunbar

**Comment by choichi** [comment]
Thanks acknowledged, will use the 10916 to perform dry run

**Comment by heungheung** [comment]
@cholho you can also use 10916 to test JavaApp lab. environment is clean 

- DBCS and JCS already created
- DB is seeded with required data
- access to the environment is until **Friday July 14**.
- you don't need to create new project in DevCS, just use the same one as created for Chris above - `APAC Cloud Test Drive - Dry Run`

**Comment by heungheung** [comment]
@choichi I took a quick look to the ICS lab and seems everything is ready.... let me know if it is good to go for a test... 😄

**Comment by choichi** [comment]
Finger cross 😄

**Comment by heungheung** [comment]
closing this as we already pass the alpha tests
