### ISSUE TITLE
End-2-End Test for workshop participants

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#12]
@cholho, at the end of lab, there will be simple until test to check if the lab is complete.   
- e.g. in Microservice, we will just use browser to go the QR code url to check if the service is working

You might want to think about if there will be a small section to talking about something like `putting all together`.  Go back to JCS to create an offer and see if Mobile App can receive, accept and obtain the QR code.

**Comment by cholho** [comment]
@heungheung 
Yes, we will have an end to end demo at the end of Test Drive as part of mobile service & application lab.
