### ISSUE TITLE
Java App - integrate with MCS

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#13]
We need a lab for JavaApp to integrate with MCS. This lab should place AFTER MCS lab - it is because participant only knows the MBE ID and Key after create it in MCS.

- In eclipse, open LoyaltyManagement/loyalty/src/main/webapp/jsp/confirm.jsp
- edit line 96 to point to MCS server
- edit line 105 to and put MBE
- edit line 109 to add MBE Anonymous key
- commit the change and push to DevCS (Git / Eclipse)
- DevCS should trigger auto build and deploy
- after successful deploy, participant can test create new offer and receive push.

**Comment by choichi** [comment]
Created a branch "lab-use" from master with the above 3 lines highlighted for pending changes.

**Comment by choichi** [comment]
Done as part of final lab and close 1st, review for correction/enhancement as new issue if any
