### ISSUE TITLE
Use locally installed Oracle Eclipse (OEPE) instead of VM

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#17]
@heungheung 

We have to update our lab guide assuming installation of OEPE (downloaded or copied from instructor) and use it throughout our labs.

**Comment by choichi** [comment]
# @heungheung 
You can just put 'use' of Eclipse, I will include install and start of OEPE from JCS lab 1 beginning.

**Comment by heungheung** [comment]
@choichi @cholho 

Mine (Microservice) use Brackets - not eclipse..... are you sure the assumption is primary use local IDE? 

I still vote for primary assumption VM. Coz I will consider local IDE means advanced user, should able to managed by themselves.

**Comment by choichi** [comment]
Both have pros and cons...
VM: Installation of VirtualBox, download/copy from instructor the several GB VM and import
OEPE: Installation of OEPE, opt with JDK together, more installation wizard options go thru

@cholho Any suggestion?

**Comment by heungheung** [comment]
Again, I also need Brackets with integration to git.

Don't tell me I need to prepare a Windows VM, figure out, screen capture and prepare instruction about "how to install Brackets and get the integration with git".... 😠

**Comment by choichi** [comment]
@cholho

It seems no choice that we better stick to VM.. 
There are 2 IDEs, we better not to complicate the lab guide further.

**Comment by cholho** [comment]
Agree^^2017. 7. 10. 오후 7:46에 Chris Choi <notifications@github.com>님이 작성:@cholho
It seems no choice that we better stick to VM..
There are 2 IDEs, we better not to complicate the lab guide further.
