### ISSUE TITLE
Length of CTD Individual Labs

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#19]
@cholho 
After your dryrun, let me know if those labs are running too long and shall be shortened. 
For JCS: Move the entire Eclipse (part 103) and code changes to after MCS lab done, as need to update MCS backend API etc
For ICS: Remove or further shortened the 'Test and Monitoring' session (304)

**Comment by cholho** [comment]
@choichi, @heungheung 
How about having one hour for 100 to 102 section of Java Apps Lab and move 103 into "Putting All Together" section of mobile services and application lab?

And for ICS, in fact I don't have a chance to do dry-run it, but I think we could remove the 'Test and Monitoring' session. We may just mention that we could do test and monitoring all integrations with some screenshots as examples at the end of 303 section.

**Comment by cholho** [comment]
@choichi, @heungheung 
For me, one hour is enough to finish Java Apps Lab (100 to 103) in case everything works fine. So, maybe we can keep 103 in Java Apps Lab to demonstrate simple CI/CD, and we can have put another CI/CD for MCS integration in "Putting All Together" section of mobile services and application lab. I need a help of Chris to make GitHub contents on this. I will try to work on Mobile lab contents from this afternoon. So I will ask Chris to work on that part when I'm ready to ask.

**Comment by choichi** [comment]
@cholho 
Thanks CholHo, then I keep 103 no change as of now, and I will re-look ICS part to see if one hour enough (otherwise break into 'long' & 'short' version to use)

For "Putting All Together", I created a separate Issue  #18 and it's assigned to me pending task :)

**Comment by choichi** [comment]
Working on a short version ICS lab at the moment

**Comment by choichi** [comment]
Short version ICS lab initially done, testing and to be merged and linked with home md

**Comment by heungheung** [comment]
I think we already put all possible efforts to shorten the labs. 

I'll propose to close this issue.

**Comment by choichi** [comment]
@heungheung agree to go ahead!
