### ISSUE TITLE
Suggest update for CloudNative_Mobile/Java Apps/100-JavaAppsLab.md

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#21]
5. When the console log-in page appears, enter the log-in credentials you entered for WebLogic Administrator when you created the service instance, e.g. `weblogic` `Welcome_1`   

@choichi since I'm not sure you will do pull before each update, I'm not going to modify it myself.

Also for both @choichi and @cholho - recommend you start leverage branching and pull request, instead of direct update.

**Comment by choichi** [comment]
Yes I do always pull if any change on GitHub, before I can do Push new stuff. 
This is mandatory controlled by the GitHub Desktop client on my Win10. 

I do branch control on any source code only before, maybe time to start the lab guide too ? 🥇 

Updated 100-JavaAppLabs.md step 5 as per stated above

**Comment by heungheung** [comment]
let's close it
