### ISSUE TITLE
Confirm if 100-JavaAppsLab.md - Create JDBC DS connectivity in JCS-WLS really needed

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#22]
As part of lab exercise OR pre-configured prior to workshop

**Comment by heungheung** [comment]
@choichi @cholho  actually, there will be some prelim works for JavaApp Lab

1. Create DB user, Create DB Tables, Seed Data
2. Create JDCS resource

Both items, I don't have a clean solution yet.

**Comment by heungheung** [comment]
just status update. we have some progress and I'll try to get it work by mid of next week, i.e. around July 19. I'll take up this issue.

**Comment by choichi** [comment]
@heungheung 
It seems like this will become steps under your Confluenece shell scripts, no need candidate to perform. 
I will wait for your closure of this issue then I remove Lab-100 and related linkage from other MDs. 

Let me know if anything else on the shell script while you are working on DB schema provisioning, just not to duplicate works... :)

**Comment by choichi** [comment]
Seems script is done, thanks
