### ISSUE TITLE
Sensible Seed Data Required

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#29]
@cholho I need seed data for the DB - right now, the data is generic & dummy. Please consider to provide data which **match** your story board and the mobile app.

- **products**: name, price (let's assume USD) and description - suggested ~5 different products
- **offers**: offer_name, required_points, offer_message, associated_product - suggested ~3 different offers seeded to DB

**Comment by cholho** [comment]
@heungheung 
Do we also need the image for product?

**Comment by cholho** [comment]
@heungheung 
Please take a look at the attached doc for seed data.
[Seed Data 4 DB_20170713.docx](https://github.com/APACTestDrive/CloudNative_Mobile/files/1143883/Seed.Data.4.DB_20170713.docx)

**Comment by heungheung** [comment]
@cholho image was stored in mobile client app. I'll only provide the product code. it makes the whole system simple. please work with SCC about the images. 

just name your images 20001.jpg, 20002.jpg, 20003.jpg, 20004.jpg respectively

**Comment by cholho** [comment]
@heungheung 
Thanks, Kenneth :laughing:

**Comment by heungheung** [comment]
FYI. 
- I will remove all double quote.... just reduce the potential problem when data in DB and/or send to mobile client via json.
- I have too many customer with many points :smile: I'll just make all required points x10 for the offers.

**Comment by cholho** [comment]
@heungheung 
Got it.~^
