### ISSUE TITLE
need to add into the JDBC create script add timeout value

### ISSUE THREAD

**Issue by heungheung** [APACTestDrive/CloudNative_Mobile#31]
as title..... if in /console, DataSource > jdbc/loyaltyDataSource > Config / Connection Pool >  Advanced > Inactive Connection Timeout: change from 0 to 30. 

It is better if we can actually put it the REST call.

**Comment by choichi** [comment]
@heungheung 
Job done @ post-create-jcs.sh v2 uploaded, adding line 119 to 129: 
......
# Configure the JDBC inactive connection timeout seconds
    VAR1=$(curl --request POST \
    --silent \
    --insecure \
    --user $WLS_ADMIN_USR:$WLS_ADMIN_PWD \
    --header "X-Requested-By:MyClient" \
    --header "Accept:application/json" \
    --header "Content-Type:application/json" \
    --data "{inactiveConnectionTimeoutSeconds: $JDBC_DS_TIMEOUT}" \
    $WLS_ADMIN_ADDR/management/weblogic/latest/edit/JDBCSystemResources/$JDBC_DS_NAME/JDBCResource/JDBCConnectionPoolParams)
    echo $VAR1
......

**Comment by choichi** [comment]
@heungheung 

Just curious does the default 0 causing problem? I didn't monitor long after Lab-103 the loyaltyapp deployed and opened.

**Comment by heungheung** [comment]
Thx! 😸
