### ISSUE TITLE
Confirm the DBCS DB instance DB host, name, user etc for CloudNative_Mobile/Java Apps/00.md

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#6]
Using 'Alpha01A-DBCS' or different one? 

Or we can skip if this is pre-provisioned with env prior to the lab

**Comment by heungheung** [comment]
The DB host should be apacctddb.compute-{identity-domain}.oraclecloud.internal 
Username is loyalty and password is actually in the db-create script, default Welcome_1

However, I'm not sure if the firewall got the rule when create JCS instance... need to test.
