### ISSUE TITLE
Link CTD Home to ICS short version lab

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#62]
If confirmed to use short version, please update the URL link to point short version /short
Both long and short version can be co-exist, as short version lab is under /short folder

**Comment by heungheung** [comment]
@choichi I believe your short version will remove the long version........

**Comment by choichi** [comment]
@heungheung the proper way which branch should I use to change the home MD file to update the pointer to integration/short md? Or clone a new one from master?

**Comment by heungheung** [comment]
- git merge master 
and 
- git rebase master 
are your friends...... alternative, you can create a pull request and merge master back to your branch.

Once your own branch is up-2-date with other files. You can make changes in your own branch, including top level files and files in other sub folder. 

If people also editing the same file, conflict will appear in the next pull request and corresponding assignee / requester should resolve the conflict

https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by heungheung** [comment]
of course..... easy way to do.... if not much changes..... create new branch, edit, push, merge, remove branch.... 😉

**Comment by choichi** [comment]
Done and close
