### ISSUE TITLE
Need to dry run JCS lab

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#7]

**Comment by heungheung** [comment]
How about this?  @cholho  please confirm

Lab-Author-Tester
JCS - Chris - CholHo
ACC - Kenneth -  Chris
ICS - Chris - Kenneth
MCS - SCC/Rayes - CholHo

**Comment by cholho** [comment]
Kenneth, 
I really like your idea. Let's do that way~~
