### ISSUE TITLE
Clean up ICS and MCS env

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#82]

**Comment by choichi** [comment]
@heungheung I better not to touch MCS env, as not sure Rayes will pre-load anything...

**Comment by heungheung** [comment]
Let me ping Rayes later tonight....

**Comment by choichi** [comment]
ICS clean up done, MCS clean up tbd

**Comment by rayeswong** [comment]
I will clean up on Monday. Also, we've got a new MCS environment. I will test it more on the new instance and share with all of you.

**Comment by rayeswong** [comment]
MCS clean up done.

**Comment by heungheung** [comment]
This is actually a place holder for Chris in particular for the Wednesday night clean up :smile:

**Comment by choichi** [comment]
Yes, keep it open 😄

**Comment by choichi** [comment]
Close temporarily :)
