### ISSUE TITLE
Create ICS Automate Clean Up script

### ISSUE THREAD

**Issue by choichi** [APACTestDrive/CloudNative_Mobile#83]
Task after India CTD

Seems possible using ICS REST v1 API (but why v2 cannot deactivate and delete Integration?)

**Comment by heungheung** [comment]
Does ICS has purge concept? MCS needs purge before using the same name.

**Comment by choichi** [comment]
No... ICS API does similar to UI... 'Deactivate', 'Delete' (in v1 only)

**Comment by choichi** [comment]
Time to start building script!

**Comment by choichi** [comment]
Script is done, tested and verified clean up on existing CTD ICS instances and uploaded to confluence.
